version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: massa_ao_ponto_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: massaaoponto
      TZ: UTC
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    command: postgres -c timezone=UTC
